import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          fontFamily: "Arial, sans-serif",
        }}
      >
        <div
          style={{
            position: "relative",
            minHeight: "100vh",
            width: "100%",
            backgroundImage: "url('/assets/images/carpage.jpeg')", // Update with your background image path
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
          }}
        >
          {/* Transparent Navbar */}
          <nav
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-around",
              padding: "10px 20px",
              backgroundColor: "rgba(0, 0, 0, 0.4)",
            }}
          >
            <div style={{ display: "flex", alignItems: "center"}}>
              <Image
                src="/assets/images/logo.png"
                alt="Logo"
                width={100}
                height={100}
              />
            </div>

            {/* Menu Options */}
            <ul
              style={{
                display: "flex",
                listStyleType: "none",
                gap: "15px",
                margin: 0,
                padding: 0,
                color: "white"
              }}
            >
              <li>
                <Link href="/car" className="text-xl font-bold bg-rgba(255, 255, 255, 0.9) px-6 py-3 rounded-lg z-1">
                  Rent a Car
                </Link>
              </li>
              <li>
                <Link
                  href="/admin"
                  className="text-xl font-bold bg-rgba(255, 255, 255, 0.9) px-6 py-3 rounded-lg"
                >
                  Admin Dashboard
                </Link>
              </li>
              <li>
                <Link
                  href="/accountant"
                  className="text-xl font-bold bg-rgba(255, 255, 255, 0.9) px-6 py-3 rounded-lg"
                >
                  Accountants
                </Link>
              </li>
              <li>
                <Link href="/dealers" className="text-xl font-bold bg-rgba(255, 255, 255, 0.9) px-6 py-3 rounded-lg">
                  Dealers
                </Link>
              </li>
            </ul>
          </nav>

          {/* Content */}
          <div
            style={{
              position: "relative",
              zIndex: 1,
            }}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
